version: "3"
services:
    db:
        container_name: postgres
        build: .
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "demoapp"
        volumes:
            - "db-data:/var/lib/postgresql/data"

volumes:
    db-data:
